export const productos = [
    {"id":1, "nombre":"Xbox Series X", "marca":"Microsoft", "imagen":"https://compass-ssl.xbox.com/assets/b9/0a/b90ad58f-9950-44a7-87fa-1ee8f0b6a90e.jpg?n=XSX_Page-Hero-0_768x792.jpg", "precio":"499", "descripcion":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus aliquet justo vitae mauris congue ultricies. Phasellus quis fermentum nunc. Integer.", "categoria":"consola", "stock":"5"},
    {"id":2, "nombre":"Xbox Series S", "marca":"Microsoft", "imagen":"https://http2.mlstatic.com/D_NQ_NP_2X_771415-MLA44492818319_012021-V.webp", "precio":"299", "descripcion":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus aliquet justo vitae mauris congue ultricies. Phasellus quis fermentum nunc. Integer.", "categoria":"consola", "stock":"10"},
    {"id":3, "nombre":"Play Station 5", "marca":"Sony", "imagen":"https://ss423.liverpool.com.mx/xl/1099815121.jpg", "precio":"499", "descripcion":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus aliquet justo vitae mauris congue ultricies. Phasellus quis fermentum nunc. Integer.", "categoria":"consola", "stock":"5"},
    {"id":4, "nombre":"Nintendo Switch", "marca":"Nintendo", "imagen":"https://res.cloudinary.com/walmart-labs/image/upload/w_960,dpr_auto,f_auto,q_auto:best/gr/images/product-images/img_large/00004549688217L.jpg", "precio":"299", "descripcion":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus aliquet justo vitae mauris congue ultricies. Phasellus quis fermentum nunc. Integer.", "categoria":"consola", "stock":"10"},
    {"id":5, "nombre":"Control Xbox", "marca":"Microsoft", "imagen":"https://http2.mlstatic.com/D_NQ_NP_985067-MLA45720839090_042021-O.jpg", "precio":"299", "descripcion":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus aliquet justo vitae mauris congue ultricies. Phasellus quis fermentum nunc. Integer.", "categoria":"accesorios", "stock":"20"},
    {"id":6, "nombre":"Control PS5", "marca":"Sony", "imagen":"https://cdn.dribbble.com/users/405330/screenshots/11354371/ps5-controller-illustration-dribbble_4x.png", "precio":"299", "descripcion":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus aliquet justo vitae mauris congue ultricies. Phasellus quis fermentum nunc. Integer.", "categoria":"accesorios", "stock":"20"},
    {"id":7, "nombre":"Tears of the Kingdom", "marca":"Nintendo", "imagen":"https://i.blogs.es/e815b1/image/original.png", "precio":"70", "descripcion":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus aliquet justo vitae mauris congue ultricies. Phasellus quis fermentum nunc. Integer.", "categoria":"videojuego", "stock":"3"},
    {"id":8, "nombre":"Persona 5 royal", "marca":"Xbox", "imagen":"https://news.xbox.com/en-us/wp-content/uploads/sites/2/2022/06/P5R_BrandedPosterArt_1080x720_v01-fa68e7b1a5046905fe98.png", "precio":"70", "descripcion":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus aliquet justo vitae mauris congue ultricies. Phasellus quis fermentum nunc. Integer.", "categoria":"videojuego", "stock":"12"},
    {"id":9, "nombre":"God of War Ragnarok", "marca":"Sony", "imagen":"https://pbs.twimg.com/media/E_FVhIUWUAAsmSP.jpg", "precio":"70", "descripcion":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus aliquet justo vitae mauris congue ultricies. Phasellus quis fermentum nunc. Integer.", "categoria":"videojuego", "stock":"5"},
];